Add support for WBTC, Tether, and Secret network
cosmostation/space-station pull request #14
Opened 2022-06-28 20:54 UTC by jkilpatr

This patch adds support for bringing Tether and WBTC from Ethereum to Gravity and also adds support for Secret network allowing the movement of weth, usdc, dai, tether, and wbtc to and from Secret.

2022-06-29 03:17 UTC, soaryong-c requested changes

2022-06-29 03:17 UTC, soaryong-c commented on src/constants/tokens/eth-gb-tokens.js
> +    address: '0xdAC17F958D2ee523a2206206994597C13D831ec7',
is it right?
0x2260FAC5E5542a773Aa44fBCfeDf7C193bc2C599

2022-06-29 03:17 UTC, soaryong-c commented on src/components/ChainSelector/index.tsx
> +  },
for support grav to secret, need add secret in 
SUPPORTED_CHAIN_MAP > [SupportedChain.GravityBridge] > toChains

2022-06-29 03:17 UTC, soaryong-c commented on src/constants/tokens/eth-gb-tokens.js
> +    logoURI: 'https://assets.coingecko.com/coins/images/325/Tether-logo.png?1598003707',
Returns Access Denied.
https://assets.coingecko.com/coins/images/325/thumb/Tether-logo.png?1598003707

2022-06-29 03:17 UTC, soaryong-c commented on src/constants/tokens/eth-gb-tokens.js
> +    logoURI: 'https://assets.coingecko.com/coins/images/7598/wrapped_bitcoin_wbtc.png?1548822744',
Returns Access Denied.

2022-06-29 03:17 UTC, soaryong-c commented on src/constants/tokens/gb-eth-tokens.js
> +    logoURI: 'https://assets.coingecko.com/coins/images/325/Tether-logo.png?1598003707',
Returns Access Denied.

2022-06-29 03:17 UTC, soaryong-c commented on src/constants/tokens/gb-eth-tokens.js
> +    logoURI: 'https://assets.coingecko.com/coins/images/325/Tether-logo.png?1598003707',
Returns Access Denied.

2022-06-29 03:17 UTC, soaryong-c commented on src/constants/tokens/eth-gb-tokens.js
> +    symbol: 'USDC',
USDC -> USDT

2022-07-11 15:35 UTC, ChristianBorst commented on src/constants/tokens/secret-gb-tokens.json
> +  "ibc/38FB1A3DA004C5F0E013432DC6CEF632000AE1387F41E09809A10DC234DE9C49": {
This might be wrong, the key on 30 matches the key of the previous entry on 23.

As well, while I was unable to query secret for Dai, Weth, and WBTC's object keys above on 2, 9, and 16 I got a response from Secret saying this is gravity0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48, aka USDC.

2022-07-13 10:25 UTC, soaryong-c requested changes

2022-07-13 10:25 UTC, soaryong-c commented on src/components/ChainSelector/index.tsx
> +      SupportedChain.Secret
Need comma.

2022-07-13 10:40 UTC, soaryong-c commented
Do you have another "Secret" logo?
Check logo in light mode please.

2022-07-13 11:02 UTC, soaryong-c requested changes

2022-07-13 11:02 UTC, soaryong-c commented on src/constants/cosmos-chains.ts
> +    [SupportedCosmosChain.GravityBridge]: 'channel-79'
channel-17?

2022-07-13 12:41 UTC, soaryong-c commented on src/constants/tokens/secret-gb-tokens.json
> +  }
need add grav ibc info.

2022-07-13 15:07 UTC, ChristianBorst commented on src/components/ChainSelector/index.tsx
> +      SupportedChain.Secret
@soaryong-c  Please see this PR here: https://github.com/cosmostation/space-station/pull/17/files#diff-09b0b80d38e0395bf0f9e8667a329b1b45563b55683ee27faf656f5da17133eeR80

2022-07-13 15:08 UTC, ChristianBorst commented on src/constants/tokens/secret-gb-tokens.json
> +  }
@soaryong-c Please see this PR here: https://github.com/cosmostation/space-station/pull/17/files#diff-9ddc9c4797844bf20852dca8fce44bf89cdb56694cee54263df2ca283564d45bR37

2022-07-13 15:33 UTC, jkilpatr commented
closing in favor of #17

2022-07-13 15:33 UTC, closed without merging